from __future__ import annotations

MAX_FRAME_AGE_SEC = 0.35

JPEG_QUALITY = 80

INSPECTION_EVERY_N_FRAMES = 5
EMPTY_SCENE_INSPECTION_EVERY_N_FRAMES = 24

MOTION_MIN_POINTS = 18
MOTION_MAX_POINTS = 220
MOTION_REINIT_POINTS = 70
MOTION_MAX_ERROR = 45.0
MOTION_RANSAC_THRESHOLD = 4.0
MOTION_MAX_STALE_FRAMES = 2
MOTION_MAX_TRANSLATION_FRACTION = 0.45
MOTION_MIN_SCALE = 0.65
MOTION_MAX_SCALE = 1.45

SESSION_SWEEP_INTERVAL_SEC = 5.0
SESSION_IDLE_TIMEOUT_SEC = 45.0
SESSION_FAILED_IDLE_TIMEOUT_SEC = 20.0
BROWSER_SESSION_FRAME_TIMEOUT_SEC = 20.0
SESSION_THREAD_JOIN_TIMEOUT_SEC = 3.0
