from __future__ import annotations

from infra.storage.file_storage import resolve_storage_path

SUPERPOINT_TORCH_WEIGHTS_PATH = resolve_storage_path("weights/superpoint_v1.pth")
LIGHTGLUE_TORCH_WEIGHTS_PATH = resolve_storage_path("weights/superpoint_lightglue.pth")

SUPERPOINT_INPUT_STRIDE = 8

SUPERPOINT_OFFLINE_MAX_SIDE: int | None = 4096
SUPERPOINT_REALTIME_MAX_SIDE: int = 640

SUPERPOINT_OFFLINE_MAX_KEYPOINTS = 4096
SUPERPOINT_REALTIME_MAX_KEYPOINTS = 512

MIN_REFERENCE_KEYPOINTS = 100

MIN_RAW_MATCHES = 18
RANSAC_REPROJECTION_THRESHOLD = 4.0
MIN_INLIERS_FOR_ALIGNMENT = 18
MAX_LIGHTGLUE_MATCH_PAIRS = 4096

ALIGNMENT_GRID_COLS = 4
ALIGNMENT_GRID_ROWS = 4
MIN_ALIGNMENT_GRID_CELLS = 3
MAX_ALIGNMENT_CELL_FRACTION = 0.45
MAX_ALIGNMENT_MEDIAN_ERROR = 10.0

IOU_MATCH_THRESHOLD = 0.25
